---
- name: deploy
  hosts: node
  tasks:
    - name: Update all packages to the latest version
      apt:
   upgrade: dist
  tasks:
    - name: install git
      apt:
        name: git
        state: latest
  tasks:
    - name: Clone repo
      git:
        repo: https://github.com/express42/reddit.git
        dest: /home/yc-user/reddit
