---
# Иначе ругается при установке (заметил совсем недавно)
- name: Upgrade bundler package to actual version (1.11.2-1)
  apt:
    name: "bundler=1.11.2-1"

- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: "/home/{{ deploy_user }}/db_config"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
  notify: reload puma

- name: Add unit file for Puma
  template:
    src: puma.service.j2
    dest: /etc/systemd/system/puma.service
  notify: reload puma

- name: enable puma
  systemd: name=puma enabled=yes
